import PLEASE_CORRECT_ERRORS_ON_FORM from "@salesforce/label/c.PLEASE_CORRECT_ERRORS_ON_FORM";
import RESERVATION_CREATED_SUCCESSFULLY from "@salesforce/label/c.RESERVATION_CREATED_SUCCESSFULLY";
import RESERVATION_UPDATED_SUCCESSFULLY from "@salesforce/label/c.RESERVATION_UPDATED_SUCCESSFULLY";
import UPDATE_RESERVATION from "@salesforce/label/c.UPDATE_RESERVATION";
import CREATE_RESERVATION from "@salesforce/label/c.CREATE_RESERVATION";
import START_OVER from "@salesforce/label/c.START_OVER";
import RESOURCE from "@salesforce/label/c.RESOURCE";

export default {
    PLEASE_CORRECT_ERRORS_ON_FORM,
    RESERVATION_CREATED_SUCCESSFULLY,
    RESERVATION_UPDATED_SUCCESSFULLY,
    UPDATE_RESERVATION,
    CREATE_RESERVATION,
    START_OVER,
    RESOURCE
};
